#作業

計算測站 C0M530 (奮起湖站) 從2006到2015年年的
  每日平均氣溫、
  每日最低溫的平均、
  每日最高溫的平均、
  每月平均氣溫、
  平均每月累積降雨?

計算最暖月的每日最高溫平均

計算最冷月的每日最低溫平均

##載入資料

###設定檔案位置
```{r}
  setwd('c:\\Users/U250/Desktop/生態資訊/ch_2.1/data/raw/')
```

###載入所有資料
```{r}
library(data.table)
#載入所有檔案
#pattern = 'auto'  設定載入檔案名稱中有auto的檔案
files <- list.files('.' , pattern = 'auto')

cwd <- list()

for( i in 1:10){
  cwd[[i]] <- fread(files[i], skip = 75)
}

head(cwd[[1]])
rm(cwd)
```

###合併資料
```{r}

for(i in 2:10){
  cwd[[1]] <- rbind(cwd[[1]], cwd[[i]])
}

allinone_cwd <- cwd[[1]]

rm(cwd)
```

###更改標題
```{r}
setnames(allinone_cwd, c('stno', 'yyyymmdd', 'PS01',
                   'TX01', 'RH01', 'WD01', 'WD02',
                   'PP01', 'SS01'))

head(allinone_cwd)
```

###清理資料
```{r}
#利用for批次將資料整理，目前只做到單一變數的重複，目標將以下程式合併成雙變數重複
#利用ifelse(判斷條件, 符合判斷條件的內容更改內容, 不符合判斷條件的內容更改內容)
c <- c(-9997, -9999, -9996, -9991, -9998, -9995)
for (i in c) {
  allinone_cwd$PS01 <- ifelse(
  allinone_cwd$PS01 == i, NA, allinone_cwd$PS01)
}
#將變數i歸零
rm(i)

for (i in c) {
  allinone_cwd$TX01  <- ifelse(
  allinone_cwd$TX01 == i, NA, allinone_cwd$TX01)
}

rm(i)

for (i in c) {
   allinone_cwd$RH01 <- ifelse(
     allinone_cwd$RH01 == i, NA, allinone_cwd$RH01)
 }

rm(i)

for (i in c) {
   allinone_cwd$WD01 <- ifelse(
     allinone_cwd$WD01 == i, NA, allinone_cwd$WD01)
 }

rm(i)

for (i in c) {
   allinone_cwd$WD02 <- ifelse(
     allinone_cwd$WD02 == i, NA, allinone_cwd$WD02)
}

rm(i)

for (i in c) {
   allinone_cwd$PP01 <- ifelse(
     allinone_cwd$PP01 == i, NA, allinone_cwd$PP01)
 }

rm(i)

for (i in c) {
   allinone_cwd$SS01 <- ifelse(
     allinone_cwd$SS01 == i, NA, allinone_cwd$SS01)
 }

rm(i)

head(allinone_cwd)

```

###挑出資料
```{r}
#使用dplyr
install.packages("dplyr")
library(dplyr)
#選取stno項中名字為C0M530的
wentdata_cwd <- filter(allinone_cwd, stno %in% c("C0M530") )

head(wentdata_cwd)
#可以將其轉為函數

```

參考：
http://genomicsclass.github.io/book/pages/dplyr_tutorial.html

###時間標記
```{r}
#建立新欄位wentdata_cwd[,內容]
#時間格式化(strptime(目標,'格式'))

as.double(wentdata_cwd$yyyymmdd)
strptime(wentdata_cwd$yyyymmdd,'%Y%m%d%H')

wentdata_cwb.dt <- data.table(wentdata_cwd)

wentdata_cwb.dt[, timestamp:=as.POSIXct(strptime(wentdata_cwb.dt$yyyymmdd-1,'%Y%m%d%H'))]

```

###計算
計算測站 C0M530 (奮起湖站) 從2006到2015年年的
1. 每日平均氣溫
2. 每日最低溫的平均
3. 每日最高溫的平均

```{R}
#TEXT 1
#利用aggregate(聚合目標, by = list()聚合條件, FUN = 使用函數)

me_ma_mi <- function(x){
  a <- c()
  a[1] <- mean(as.double(x), na.rm = TRUE )
  a[2] <- max(x, na.rm = TRUE)
  a[3] <- min(x, na.rm = TRUE)
  return(a)
  }

day_temper_info <- aggregate(as.numeric(wentdata_cwb.dt$TX01), 
                     by = list(
                       format.Date(wentdata_cwb.dt$timestamp, '%Y-%m-%d')
                       ),  FUN = me_ma_mi
                     )
#由於直行到現在day_temper_info成為三維格式，因此表格抓不出來(只會呈現每一維第一列)
#將其轉換成矩陣，再轉成table
day_temper_info <- as.data.frame(as.matrix(day_temper_info))


head(day_temper_info)
setnames(day_temper_info, c('day', 'DTM', 'DMax','Dmin'))
head(day_temper_info)

#

rm(day_temper_info.df)
rm(a)

```

4. 每月平均氣溫

```{r}
m_mean <- function(x){
  a <- c()
  a[1] <- mean(as.double(x), na.rm = TRUE )
  return(a)
}

m_temper_info <- aggregate(as.numeric(wentdata_cwb.dt$TX01), 
                     by = list(
                       format.Date(wentdata_cwb.dt$timestamp, '%Y-%m')
                       ),  FUN = m_mean
                     )

m_temper_info <- as.data.frame(as.matrix(m_temper_info))

head(m_temper_info)
setnames(m_temper_info, c('Month', 'MTM'))
head(m_temper_info)

```

5. 平均每月累積降雨
```{R}

m_sum <- function(x){
  a <- c()
  a[1] <- sum(as.double(x), na.rm = TRUE )
  return(a)
}

m_rain_info <- aggregate(as.numeric(wentdata_cwb.dt$PP01), 
                     by = list(
                       format.Date(wentdata_cwb.dt$timestamp, '%Y-%m')
                       ),  FUN = m_sum
                     )

m_rain_info <- as.data.frame(as.matrix(m_rain_info))

head(m_rain_info)
setnames(m_rain_info, c('Month', 'MPS'))
head(m_rain_info)

```
as.double(wentdata_cwd$yyyymmdd)
strptime(wentdata_cwd$yyyymmdd,'%Y%m%d%H')
計算最暖月的每日最高溫平均
```{r}
#將資料排序
TEXT <- m_temper_info %>% arrange(MTM) 
#取出月份
went_hot_mouth <- TEXT[length(TEXT$Month),'Month']
#轉換文字
went_hot_mouth_ch <- 
  substr(as.matrix(TEXT[length(TEXT$Month),'Month'])[1, 1], 1, 7)
#轉換時間(失敗)
as.matrix(went_hot_mouth_ch)
as.Date(as.matrix(went_hot_mouth_ch) , format = "%Y-%m")
as.POSIXct(strptime(as.matrix(went_hot_mouth_ch), '%Y-%m'))
strptime(went_hot_mouth_ch, '%Y-%m')

#換方法
##轉格式
day_temper_info_ch <- as.data.table(day_temper_info)
##增加欄位
day_temper_info_ch[, Mouth:=substr(day_temper_info_ch$day, 1, 7)]
##篩選
medmt_data <- day_temper_info_ch[day_temper_info_ch$Mouth == went_hot_mouth_ch]
##除錯-Inf
medmt_data$DMax <- ifelse(
  c(as.character(medmt_data$DMax)) == '     -Inf',
  NA, c(as.character(medmt_data$DMax)))
#解
most_hot_mouth_mean <- m_mean(as.numeric(c(medmt_data$DMax)))


```

計算最冷月的每日最低溫平均
```{r}
#將資料排序
TEXT2 <- m_temper_info %>% arrange(MTM) 
#取出月份
went_hot_mouth <- TEXT[1,'Month']
#轉換文字
went_cold_mouth_ch <- 
  substr(as.matrix(TEXT[length(TEXT$Month),'Month'])[1, 1], 1, 7)

##轉格式,增加欄位做過了

##篩選
medmt_data <- day_temper_info_ch[day_temper_info_ch$Mouth == went_cold_mouth_ch]
##除錯Inf
medmt_data$Dmin <- ifelse(
  c(as.character(medmt_data$Dmin)) == '      Inf',
  NA, c(as.character(medmt_data$Dmin)))
#解
most_cold_mouth_mean <- m_mean(as.numeric(c(medmt_data$Dmin)))

```
